version: '3.8'

networks:
  default:


services:
  db:
    image: mysql:latest
    container_name: users
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vatech_db
    ports:
      - "3306:3306"
    volumes:
      - "./.data/db:/var/lib/mysql"
