name: Payments Application CI/CD

on:
  push:
    branches:
      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java (e.g., for Spring Boot)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Change to your Java version
          distribution: 'temurin'

      # Install dependencies and build the application
      - name: Build Project
        run: |
          mvn clean install

      # Run Tests
      - name: Run Tests
        run: |
          mvn test

#  deploy:
#    name: Deploy to Server
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      # Checkout the repository
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      # Deploy the application
#      - name: Deploy Application
#        env:
#          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
#          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
#          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
#        run: |
#          ssh -i $DEPLOY_KEY $DEPLOY_USER@$DEPLOY_HOST 'bash -s' < ./deploy.sh